config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :meals do
    resources :choices, only: [:new, :create,]
  end
  resources :choices, only: [:update, :edit,]
  resources :restaurants, only: [:show]
  get '/dashboard', to: 'dashboards#dashboard', as: :dashboard
  get '/preferences', to: 'meals#preferences', as: :preferences
  get '/tagged', to: "meals#tagged", as: :tagged



#  get "external" => "http:/www.google.com"
end

app/views/pages/home.html.erb
<% if @choice&.unrated? %>
  <% "it's inside"%>
  <%= render 'shared/modal_rating',  choice: @choice %>
<% end %>
<div class="body">
    <h2>Food on Rails</h2>
  <div class="bg-design">
    <h4>Healthiest Choice in<br><span class="color-red"><strong>Un</strong></span>healthy Situations</h4>
  </div>
    <div class="container-landing">
      <div class="card-landing">
        <div class="btn-landing">
          <%= link_to meals_path(tag: 'Food') do %>
            <i class="fas fa-utensils"></i><br>
          <% end %>
        </div>
        <p class="btn-caption"><strong>I'm Hungry</strong></p>
      </div>
      <div class="card-landing  btn-mrgn-left">
        <div class="btn-landing btn-padding-left">
          <%= link_to meals_path(tag: 'Drinks') do %>
            <i class="fas fa-mug-hot"></i><br>
          <% end %>
        </div>
        <p class="btn-caption"><strong>I'm Thirsty</strong></p>
      </div>
    </div>
  </div>
</div>