config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :meals do
    resources :choices, only: [:new, :create,]
  end
  resources :choices, only: [:update, :edit,]
  resources :restaurants, only: [:show]
  get '/dashboard', to: 'dashboards#dashboard', as: :dashboard
  get '/preferences', to: 'meals#preferences', as: :preferences
  get '/tagged', to: "meals#tagged", as: :tagged



#  get "external" => "http:/www.google.com"
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :restaurant
  has_many :locations, through: :restaurant
  has_many :choices, dependent: :destroy
  validates :name, presence: true, uniqueness: { scope: :restaurant }
  # validates :price, presence: true
  # validates :score, presence: true
  validate :validate_attrlist
  acts_as_taggable_on :tags
  has_one_attached :photo
  scope :max_calories_meal, -> { order(calories: :desc).first }
  scope :max_fat_meal, -> { order(fat: :desc).first }
  scope :max_sodium_meal, -> { order(sodium: :desc).first }
  scope :min_protein_meal, -> { order(proteins: :asc).first }
  scope :max_carbs_meal, -> { order(carbohydrates: :desc).first }

  include PgSearch::Model
  pg_search_scope :search_by_preferences,
                  against: :name,
                  associated_against: {
                    restaurant: :name
                  },
                  using: {
                    tsearch: { prefix: true } # <-- now `superman batm` will return something!
                  }

  def validate_attrlist
    if calories.blank? && proteins.blank? && carbohydrates.blank? && fat.blank? && sodium.blank?
      errors[:nutrition_infos] << "Can't be blank"
    end
  end

  # For meal show column graph
  def calorie_cutoffs
    case calories
    when 0...400 then :'#246A73'
    when 400..600 then :'#E87EA1'
    when 600..1000 then :'#F8F32B'
    end
  end

  def protein_cutoffs
    case proteins
    when 0...10 then :'#F40000'
    when 10..20 then :'#FCBA04'
    when 20..1000 then :'#8CD867'
    end
  end

  def fat_cutoffs
    case fat
    when 0...10 then :'#8CD867'
    when 10..20 then :'#FCBA04'
    when 20..1000 then :'#F40000'
    end
  end

  def sodium_cutoffs
    case sodium
    when 0...1.5 then :'#8CD867'
    when 1.5..2.5 then :'#FCBA04'
    when 2.5..100 then :'#F40000'
    end
  end

  def carbs_cutoffs
    case carbohydrates
    when 0...30 then :'#8CD867'
    when 30..50 then :'#FCBA04'
    when 50..1000 then :'#F40000'
    end
  end

  # Food on Rails top secret special food & drink score algorithm
  # FOOD SCORES
  # CALORIES
  def calories_cutoff_score
    @cutoff_score = 0
    if calories < 400
      return @cutoff_score + 20
    elsif calories > 800
      return @cutoff_score
    else
      return @cutoff_score + 10
    end
  end

  # CARBOHYDRATES
  def carb_ratio_score
    @ratio_score = 0
    if carbohydrates
      if ((carbohydrates * 4) / calories) * 100 > 65
        return @ratio_score
      elsif ((carbohydrates * 4) / calories) * 100 < 45
        return @ratio_score + 5
      else
        return @ratio_score + 10
      end
    else
      @ratio_score
    end
  end

  def carb_bonus_score
    @bonus_score = 0
    if carbohydrates
      if (30..50).cover?(carbohydrates)
        if 50 - carbohydrates < 10
          return @bonus_score + ((50 - carbohydrates) / 2)
        else
          return @bonus_score + 5
        end
      elsif carbohydrates > 50
        return @bonus_score
      else
        return @bonus_score + 10
      end
    else
      @bonus_score
    end
  end

  def carb_score
    return carb_bonus_score + carb_ratio_score
  end

  # FAT
  def fat_ratio_score
    @ratio_score = 0
    if fat
      if ((fat * 9) / calories) * 100 > 35
        return @ratio_score
      elsif ((fat * 9) / calories) * 100 < 20
        return @ratio_score + 5
      else
        return @ratio_score + 10
      end
    else
      @ratio_score
    end
  end

  def fat_bonus_score
    @bonus_score = 0
    if fat
      if (10..20).cover?(fat)
        if 20 - fat < 5
          return @bonus_score + (20 - fat)
        else
          return @bonus_score + 5
        end
      elsif fat < 10
        return @bonus_score + 10
      else
        return @bonus_score
      end
    else
      @bonus_score
    end
  end

  def fat_score
    return fat_bonus_score + fat_ratio_score
  end

  # PROTEIN
  def protein_ratio_score
    @ratio_score = 0
    if proteins
      if ((proteins * 4) / calories) * 100 < 10
        return @ratio_score
      elsif ((proteins * 4) / calories) * 100 > 35
        return @ratio_score + 5
      else
        return @ratio_score + 10
      end
    else
      @ratio_score
    end
  end

  def protein_bonus_score
    @bonus_score = 0
    if proteins
      if (10..20).cover?(proteins)
        if proteins - 10 < 5
          return @bonus_score + (proteins - 10)
        else
          return @bonus_score + 5
        end
      elsif proteins > 20
        return @bonus_score + 10
      else
        return @bonus_score
      end
    else
      @bonus_score
    end
  end

  def protein_score
    return protein_bonus_score + protein_ratio_score
  end

  # SODIUM
  def sodium_cutoff_score
    @cutoff_score = 0
    if sodium
      if sodium < 1
        return @cutoff_score + 10
      elsif sodium > 2
        return @cutoff_score
      else
        return @cutoff_score + 5
      end
    else
      @cutoff_score
    end
  end

  # TOTAL SCORE
  def food_score
    (sodium_cutoff_score + calories_cutoff_score + carb_score + protein_score + fat_score).round
  end

  # DRINK SCORES

  # CALORIES
  def drink_calories_cutoff_score
    @cutoff_score = 0
    if calories < 100
      return @cutoff_score + 30
    elsif calories > 200
      return @cutoff_score
    else
      return @cutoff_score + 15
    end
  end

  # SODIUM
  def drink_sodium_cutoff_score
    @cutoff_score = 0
    if sodium
      if sodium < 1
        return @cutoff_score + 10
      elsif sodium > 2
        return @cutoff_score
      else
        return @cutoff_score + 5
      end
    else
      @cutoff_score
    end
  end

  # CARBS
  def drink_carb_ratio_score
    @ratio_score = 0
    if carbohydrates
      if ((carbohydrates * 4) / calories) * 100 > 65
        return @ratio_score
      elsif ((carbohydrates * 4) / calories) * 100 < 45
        return @ratio_score + 3
      else
        return @ratio_score + 5
      end
    else
      @ratio_score
    end
  end

  def drink_carb_bonus_score
    @bonus_score = 0
    if carbohydrates
      if (5..10).cover?(carbohydrates)
        return @bonus_score + 10 + (10 - carbohydrates)
      elsif carbohydrates > 10
        return @bonus_score
      else
        return @bonus_score + 20
      end
    else
      @bonus_score
    end
  end

  def drink_carb_score
    return drink_carb_bonus_score + drink_carb_ratio_score
  end

  # FAT
  def drink_fat_ratio_score
    @ratio_score = 0
    if fat
      if ((fat * 9) / calories) * 100 > 35
        return @ratio_score
      elsif ((fat * 9) / calories) * 100 < 20
        return @ratio_score + 3
      else
        return @ratio_score + 5
      end
    else
      @ratio_score
    end
  end

  def drink_fat_bonus_score
    @bonus_score = 0
    if fat
      if (1..3).cover?(fat)
        return @bonus_score + 10 + ((3 - fat) * 2)
      elsif fat < 1
        return @bonus_score + 20
      else
        return @bonus_score
      end
    else
      @bonus_score
    end
  end

  def drink_fat_score
    return drink_fat_bonus_score + drink_fat_ratio_score
  end

  # PROTEIN
  def drink_protein_ratio_score
    @ratio_score = 0
    if proteins
      if ((proteins * 4) / calories) * 100 < 10
        return @ratio_score
      elsif ((proteins * 4) / calories) * 100 > 35
        return @ratio_score + 3
      else
        return @ratio_score + 5
      end
    else
      @ratio_score
    end
  end

  def drink_protein_bonus_score
    @bonus_score = 0
    if proteins
      if (1..5).cover?(proteins)
        return @bonus_score + (proteins - 1)
      elsif proteins > 5
        return @bonus_score + 5
      else
        return @bonus_score
      end
    else
      @bonus_score
    end
  end

  def drink_protein_score
    return drink_protein_bonus_score + drink_protein_ratio_score
  end

  # TOTAL SCORE
  def drink_score
    (drink_sodium_cutoff_score + drink_calories_cutoff_score + drink_carb_score + drink_protein_score + drink_fat_score).round
  end
end

app/controllers/meals_controller.rb
require "open-uri"
class MealsController < ApplicationController
  skip_before_action :authenticate_user!, only: :preferences

  def index
    @meals = policy_scope(Meal)
    @choice = Choice.new
    if params[:tag] == 'Drinks'
      @switch = true
      @meals = @meals.tagged_with(params[:tag])
      if params[:query].present?
        @meals = search(@meals, params[:query])
        @meals = @meals.sort_by { |meal| -meal.drink_score }.first(20)
      else
        @meals = @meals.sort_by { |meal| -meal.drink_score }.first(20)
        @user = current_user
      end
    else
      @meals = @meals.tagged_with('Drinks', exclude: true)
      if params[:query].present?
        @meals = search(@meals, params[:query])
        @meals = @meals.sort_by { |meal| -meal.food_score }.first(20)
      else
        @meals = @meals.sort_by { |meal| -meal.food_score }.first(20)
        @user = current_user
      end
    end
    @current_position =
      {
        lat: params['lat'].to_f,
        lng: params['lon'].to_f,
        image_url: helpers.asset_url('user_position.png')
      }
    @locations = Location.joins(:meals).where(meals: { id: @meals })
    @markers = @locations.geocoded.map do |location|
      {
        lat: location.latitude,
        lng: location.longitude,
        image_url: helpers.cl_image_path(location.restaurant.photo.key)
      }
    end
  end

  def search(meals, params)
    search = meals.search_by_preferences(params)
    tag = meals.tagged_with(params)
    join = search + tag
    @results = join.uniq
  end

  def show
    @meal = Meal.find(params[:id])
    authorize @meal
    @choice = Choice.new
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
    if @meal.save
      redirect_to meals_path
    else
      render :new
    end
  end

  def preferences
    skip_authorization
  end

  def edit
    @meal = Meal.find(params[:id])
    authorize @meal
  end

  def update
    @meal = Meal.find(params[:id])
    file = URI.open(params[:photo])
    @meal.photo.attach(io: file, filename: "meal.png", content_type: 'image/png')
    authorize @meal
    @meal.save
    redirect_to meals_path
  end

  private

  def meal_params
    params.require(:meal).permit(:name, :price, :calories, :protein, :fat, :carbohydrates, :sodium, tag_list: [])
  end
end

# current_user.goal = params[:goal]
# current_user.update(goal: params[:goal])
# case current_user.goal
# when current_user.goal = "lose_weight"
#   if params[:query].present?
#     search = @meals.search_by_preferences(params[:query])
#     tag = @meals.tagged_with(params[:query])
#     join = search + tag
#     @results = join.uniq
#     @meals = @results.sort_by { |meal| meal.calories }.first(3)
#   else
#     @meals = @meals.sort_by { |meal| meal.calories }.first(3)
#     @user = current_user
#   end

app/views/meals/edit.html.erb
<%= @meal.name%>
<%= simple_form_for @meal do |f| %>
  <%= text_field_tag :photo %>
  <%= f.submit %>
<% end %>

app/views/meals/index.html.erb
<%= render 'shared/loading' %>
<div class="desktop-view">
  
  <div class="container-meal-index">
    <div class="container-body">
      <div class="form-preferences">
        <i> Want to eat something in particular? </i>
        <%= form_tag meals_path, method: :get do %>
          <div class="form-meal">
            <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Burger, salad, chicken, fish..."
            %>
            <%= submit_tag "Search", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
      <% @meals.first(3).each do |meal| %>
        <div class="card-choice">
          <%= cl_image_tag(meal.photo.key, height: 80, width: 80, crop: :pad) if meal.photo.attached? %>
          <div class="card-choice-description">
            <h3 class="heavy-text"><%= meal.name %></h3>
            <p class="light-text"><%= meal.restaurant.name %></p>
            <%= link_to "MORE INFO", meal_path(meal, goal: params[:goal]), class: "text-btn-label font-align-left" %>
          </div>
          <% if @switch.nil? %>
            <div class="card-choice-middle" style="background-color: <%= get_score_background(meal.food_score) %>;">
              <p class="index-score <%= get_score_class(meal.food_score) %>"><%= meal.food_score %></p>
              <i class="<%= get_score_class(meal.food_score) %> fas fa-<%= get_score_icon(meal.food_score) %>"></i>
            </div>
          <% else %>
            <div class="card-choice-middle" style="background-color: <%= get_score_background(meal.drink_score) %>;">
              <p class="index-score <%= get_score_class(meal.drink_score) %>"><%= meal.drink_score %></p>
              <i class="<%= get_score_class(meal.drink_score) %> fas fa-<%= get_score_icon(meal.drink_score) %>"></i>
            </div>
          <% end %>
          <div class="card-choice-right">
            <%= simple_form_for [ meal, @choice ] do |f| %>
              <%=  hidden_field_tag :lat, nil, class: "hidden-lat" %>
              <%=  hidden_field_tag :lon, nil, class: "hidden-lon" %>
              <%= f.association :meal, as: :hidden, input_html: { value: meal.id }%>
              <%= f.association :user, as: :hidden, input_html: { value: current_user.id }%>
              <%= button_tag "GO", type: :submit, class: "btn btn-primary" do %>
                <i class="fas fa-map-marker-alt"></i>
                <p>GO</p>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
      <div>
        <div class="more-card-choices" data-controller="load">
          <div class="btn-centered">
            <button class="btn" data-load-target="button" data-action="click->load#loadMore">More</button>
          </div>
          <div class="cards-choice hidden" data-load-target="cards">
            <% @meals.drop(3).each do |meal| %>
              <div class="card-choice">
                <%= cl_image_tag(meal.photo.key, height: 80, width: 80, crop: :pad) if meal.photo.attached?  %>
                <div class="card-choice-description">
                  <h3 class="heavy-text"><%= meal.name %></h3>
                  <p class="light-text"><%= meal.restaurant.name %></p>
                  <%= link_to "MORE INFO", meal_path(meal, goal: params[:goal]), class: "text-btn-label font-align-left" %>
                </div>
                <% if @switch.nil? %>
                  <div class="card-choice-middle" style="background-color: <%= get_score_background(meal.food_score) %>;">
                    <p class="index-score <%= get_score_class(meal.food_score) %>"><%= meal.food_score %></p>
                    <i class="<%= get_score_class(meal.food_score) %> fas fa-<%= get_score_icon(meal.food_score) %>"></i>
                  </div>
                <% else %>
                  <div class="card-choice-middle" style="background-color: <%= get_score_background(meal.drink_score) %>;">
                    <p class="index-score <%= get_score_class(meal.drink_score) %>"><%= meal.drink_score %></p>
                    <i class="<%= get_score_class(meal.drink_score) %> fas fa-<%= get_score_icon(meal.drink_score) %>"></i>
                  </div>
                <% end %>
                <div class="card-choice-right">
                  <%= simple_form_for [ meal, @choice ] do |f| %>
                    <%=  hidden_field_tag :lat, nil, class: "hidden-lat" %>
                    <%=  hidden_field_tag :lon, nil, class: "hidden-lon" %>
                    <%= f.association :meal, as: :hidden, input_html: { value: meal.id }%>
                    <%= f.association :user, as: :hidden, input_html: { value: current_user.id }%>
                    <%= button_tag "GO", type: :submit, class: "btn btn-primary" do %>
                      <i class="fas fa-map-marker-alt"></i>
                      <p>GO</p>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="map"
      data-markers="<%= @markers.to_json %>"
      data-current_position="<%= @current_position.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/meals/preferences.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-6">
      <div class="form-preferences">
        <%= form_tag meals_path, method: :get do %>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "What do you want to eat?"
        %>
          <%= submit_tag "Search", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/meals/show.html.erb
<div class="container-info-body">
  <div class="card-detail card-meal-banner card-detail-show">
    <%= cl_image_tag(@meal.photo.key, crop: :fill) if @meal.photo.attached?  %>
    <h2><%= @meal.name%></h2>
    <%= cl_image_tag(@meal.restaurant.photo.key, crop: :fill, class: "show-restaurant") if @meal.restaurant.photo.attached? %>
  </div>
  <hr>
  <div class="container-nutritional-info">
    <div class="meals-show-form">
      <%= simple_form_for [ @meal, @choice ] do |f| %>
        <%= f.association :meal, as: :hidden, input_html: { value: @meal.id }%>
        <%= f.association :user, as: :hidden, input_html: { value: current_user.id }%>
        <%= button_tag "GO", type: :submit, class: "show-btn btn-primary" do %>
          <p>GO</p>
          <i class="fas fa-map-marker-alt"></i>
        <% end %>
      <% end %>
    </div>
    <div class="container-calories-graphs">
      <h3 class="center-text">Recommended Calories Per Day</h3>
      <%= pie_chart [["This Meal", @meal.calories], ["Remaining Calories", 2000 - @meal.calories]], colors: [ '#FF673B', '#FFF0EB' ], suffix: " kcal", legend: "bottom" %>
      <div class="calories">
        <p>kcal:</p>
        <h3><%= @meal.calories %></h3>
      </div>
    </div>
    <div class="container-macros-graphs">
      <h3 class="center-text">Nutrients vs. Average</h3>
      <%= column_chart [{name: "Protein", data: {Protein: @meal.proteins}}, {name: "Avg. Protein", data: {Protein: Meal.average(:proteins)}}, {name: "Carbs", data: {Carbs: @meal.carbohydrates}}, {name: "Avg. Carbs", data: {Carbs: Meal.average(:carbohydrates)}}, {name: "Fats", data: {Fats: @meal.fat}}, {name: "Avg. Fat", data: {Fats: Meal.average(:fat)}}, {name: "Sodium", data: {Sodium: @meal.sodium}}, {name: "Avg Sodium", data: {Sodium: Meal.average(:sodium)}}], colors: [ @meal.protein_cutoffs, "#FFB19A", @meal.carbs_cutoffs, "#FFB19A", @meal.fat_cutoffs, "#FFB19A", @meal.sodium_cutoffs, "#FFB19A" ], library: { scales: { yAxes: [{ gridLines: { display: false }, ticks: { display: false }}]}}, suffix: " grams", legend: false %>
      <div class="legend">
        <div class="legend-left">
          <p>This meal</p>
          <div id="legend-left-key">
            <div id="legend-healthy">
              <p id="legend-healthy-bar"></p>
              <p id="legend-text">Good</p>
            </div>
            <div id="legend-moderate">
              <p id="legend-moderate-bar"></p>
              <p id="legend-text">Moderate</p>
            </div>
            <div id="legend-worst">
              <p id="legend-worst-bar"></p>
              <p id="legend-text">Bad</p>
            </div>
          </div>
        </div>
        <div class="legend-right">
          <p>All options</p>
          <div id="legend-average">
            <p id="legend-average-bar"></p>
            <p id="legend-text">Average</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>